spring:
  datasource:
    url: jdbc:mysql://localhost:3306/receitasDB?createDatabaseIfNotExist=true
    username: root
    password: root
  profiles:
    active: dev
    jpa:
      hibernate:
        ddl-auto: update
    jackson:
      default-property-inclusion: non_ null